### ISSUE TITLE
Add Ubuntu packages

### ISSUE THREAD

**Issue by bkircher** [otris/jsrdbg#1]
Create dpkg build files for the last two Ubuntu LTS versions, 14.04 and 16.04, and add them to the `contrib/` folder.

Starting point:
http://packaging.ubuntu.com/html/packaging-new-software.html

Also, provide two Vagrant files for creating these packages from scratch. See here for a starter:
https://github.com/bkircher/vagrant-files/tree/master/makepkg-jsrdbg-fedora

**Comment by bkircher** [comment]
@m-Schlitzer Could you get this done by Monday, Nov 7th?

**Comment by m-Schlitzer** [comment]
Sure

**Comment by bkircher** [comment]
👍

**Comment by bkircher** [comment]
Done
